# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

matrix:
  include:
    - os: linux
      r: release
    - os: linux
      r: devel
      env: R_CODECOV=true

r_build_args: '--no-build-vignettes --no-manual'
r_check_args: '--no-build-vignettes --no-examples'

env:
   global:
     - NOT_CRAN="true"
     - _R_CHECK_FORCE_SUGGESTS_=false
     
warnings_are_errors: true

r_github_packages:
  - jimhester/covr
  - richfitz/remake

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::coveralls()'; fi
  
notifications:
  email:
    on_success: change
    on_failure: change
