## Shared Cache {.tabset .tabset-fade .tabset-pills}

Alison Appling, July 31, 2018;  
Jake Zwart, February 4, 2019

---
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Shared cache}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---
<head>
<style>
data {color: #CA3542;}
ind {color: #FEBC38;}
build {color: #697F98;} 
target {color: #37AFA9}
</style>
</head>

  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache=FALSE, collapse=TRUE)
```


### Terms and concept

####Terms

* <data>**Data file**</data>: files used as input for or generated as output by computing (e.g. streamgage data, geospatial data, site metadata, modeling results) 
* <ind>**Indicator file**</ind>: git-versioned files that promise the analyst that the data file exists remotely 
* <build>**Build status file**</build>: git-versioned files that represent the collective project build status (e.g. which targets have been built and/or are up-to-date) 
* <target>**Target**</target>: points or steps in the analysis that can be files or R objects. Many of the targets in a shared cache project will be <ind>indicator files</ind>. 

####Concept

A **s**hared **c**ache (**sc** of `scmake`) is a cloud data storage location where raw, intermediate, and/or final data products from an analysis project are contributed to and accessible by multiple analysts. Not all scipiper projects will use a shared cache.

<data>**Data files**</data> only _need_ to be local when the analyst is computing with the <data>**data file**</data>. <ind>**Indicator files**</ind> (`.ind`) represent the remote shared cache among project participants. This allows analyst #1 to compute steps `A` and `B` (e.g. streamflow data pull [step `A`] and aggreagation [step `B`]), upload output from steps `A` and `B` to the project's shared cache, and analyst #2 can use the output from step `B` without redoing the computing performed by analyst #1. 

Workflow dependencies are connected via the <ind>**indicator files**</ind>. Recipes (e.g. R function) that push <data>**data files**</data> to the shared cache create <ind>**indicator files**</ind>, and these <ind>**indicator files**</ind> can be used in other recipes to pull down <data>**data files**</data> from the shared cache using `scipiper` functions such as `gd_get()` (if data is not already available locally). 

<build>**Build files**</build> tell remake if the <ind>**indicator files**</ind> and their dependencies are up-to-date. <target>**Targets**</target> that are not saved as <ind>**indicator**</ind> or <data>**data**</data> files (e.g. R objects) will not have a <build>**build status file**</build> and will be excuted every time it is called.  

Example of `.ind` file dependency where the function `select_sites()` (code snippet below yaml code) uses `gd_get()` and the <ind>**indicator file**</ind> `1_data/out/compiled_data.rds.ind` as a dependency to pull down the <data>**data file**</data> (`compiled_data.rds`) from the shared cache. 
<pre>
target_default: <target>1_data</target>

sources: 
  - 1_data/src/gather_data.R
  - 1_data/src/select_sites.R

targets:

  <target>1_data:</target>
     depends:
      - <ind>1_data/out/compiled_data.rds.ind</ind>
      - <ind>1_data/out/selected_sites.rds.ind</ind>

  <ind>1_data/out/compiled_data.rds.ind:</ind>
    command: gather_and_share_stream_data(
      ind_file = target_name,
      state = I("WI"), 
      gd_config = <data>'lib/cfg/gd_config.yml'</data>)

  <ind>1_data/out/selected_sites.rds.ind:</ind>
    command: select_sites(
      ind_file = target_name,
      input_ind_file = <ind>'1_data/out/compiled_data.rds.ind'</ind>,
      gd_config = <data>'lib/cfg/gd_config.yml'</data>)
</pre>

Functions used in the above code snippet: 

<pre> 
gather_and_share_stream_data = function(<ind>ind_file</ind>, state, <data>gd_config</data>){
  
  <data>temp</data> <- readNWISdata(stateCd = state, parameterCd = '00010', service = 'dv')

  data_file <- as_data_file(<ind>ind_file</ind>) # convert indicator file to data file format (drops .ind suffix)
  saveRDS(<data>temp</data>, data_file)
  gd_put(remote_ind = <ind>ind_file</ind>, local_source = <data>data_file</data>, config_file = <data>gd_config</data>)
}

select_sites = function(<ind>ind_file</ind>, <ind>input_ind_file</ind>, <data>gd_config</data>){

  <data>temp</data> = readRDS(sc_retrieve(<ind>input_ind_file</ind>))
  
  <data>temp_sites</data> <- <data>temp</data> %>%
    dplyr::filter(
      dateTime > as.POSIXct('2012-01-01')) %>%
    dplyr::select(site_no, dateTime) 
    
  data_file <- as_data_file(<ind>ind_file</ind>)
  saveRDS(<data>temp_sites</data>, data_file)
  gd_put(remote_ind = <ind>ind_file</ind>, local_source = <data>data_file</data>, config_file = <data>gd_config</data>)
}

</pre> 


### Guidelines

####Projects using a shared cache should follow these guidelines:

* Use <ind>**indicator files**</ind> (usually an `.ind` suffix) to represent most or all of the chain of connected <target>**targets**</target> within your remake files. Each `.ind` file should be one of two products of a recipe (e.g. R function call), where the other product is the creation of a <data>**data file**</data>, either locally and/or in the shared cache. The <ind>**indicator files**</ind> are the only products that are declared to `remake`, while the <data>**data files**</data> remain hidden. This allows the <ind>**indicator files**</ind> to indirectly represent the <data>**data files**</data> to `remake` thereby enabling compatibility between `remake` and the shared cache. 

* Always build <target>**targets**</target> using `scipiper::scmake()` rather than `remake::make()`. Though the functions are outwardly very similar, `scmake()` maintains an extra layer of metadata that allows multiple users to share a single project <build>**build status**</build> (e.g., "file x.rds.ind is up to date; file y.rds.ind is out of date"). In a shared-cache project, you should not even need to load the `remake` package directly.

* Generally avoid using R objects as `remake/scmake` <target>**targets**</target>...but if you must, usually for convenience or conciseness of the workflow plan, recognize that R objects must be built by every analyst. So if a target takes a non-trivial length of time to build, or if it depends on large volumes of <data>**data**</data> as input, that target should usually be a file rather than an R object.

* `git commit` all <ind>**indicator files**</ind> and <build>**build files**</build> (with occasional exception of <ind>**indicator files**</ind> within a task plan; those require additional thought). `git ignore` all <data>**data files**</data> unless they are small enough to store in git/GitHub, such as small, text-based, and typically hand-curated <data>**data files**</data> (e.g. a <data>**data file**</data> that matches NHD lake ID's to collaborator-provided <data>**data files**</data>). <data>**Data files**</data> that are  necessary to pipeline basic functions should also be committed (e.g. <data>**gd_config.yml**</data>). 

* To force a rebuild, either use the `force=TRUE` argument to `scmake()` or use `scdel()` to delete <ind>**indicator files**</ind>. There's seldom any benefit to deleting <data>**data files**</data> (by any method); usually deleting the <ind>**indicator files**</ind> is plenty. When deleting <ind>**indicator files**</ind>, `force=TRUE` or `scdel()` are preferable to directly deleting the `.ind` files because if only the `.ind` files are deleted, the `scipiper` database may fail to update properly when the `.ind` files are rebuilt.

####How many <target>targets</target> should I use per <data>data file</data>?

#####3 <target>**target**</target> method: 
1. create a <data>**data file**</data> 
2. push a <data>**data file**</data> and create an <ind>**indicator file**</ind> 
3. retrive the <data>**data file**</data> 

######Advantages
- <data>**Data**</data> and <ind>**indicator**</ind> file creation is verbose and clear
- Helps with fault tolerance by splitting tasks into multiple targets 
- This method may be necessary when using standard functions for data creation or retrieval  

<pre>
targets:

  <data>1_data/tmp/nitrate_data_pull.rds.ind:</data>
    command: gather_stream_data(
      file = target_name,
      siteNumber = I('01118500'),
      parameterCd = I('00630'),
      startDate = I('1980-01-01'),
      endDate = I('2016-01-01'))

  <ind>1_data/out/nitrate_data_pull.rds.ind:</ind>
    command: gd_put(
      remote_ind = target_name,
      local_source = <data>'1_data/tmp/nitrate_data_pull.rds.ind'</data>,
      gd_config = <data>'lib/cfg/gd_config.yml'</data>)
      
  <data>1_data/out/nitrate_data_pull.rds:</data>
    command: gd_get(<ind>'1_data/out/nitrate_data_pull.rds.ind'</ind>, config_file = <data>'lib/cfg/gd_config.yml'</data>)

</pre>

#####2 <target>**target**</target> method: 
1. push a <data>**data file**</data> and create an <ind>**indicator file**</ind> 
2. retrive the <data>**data file**</data> 

######Advantages
- More concise code and fewer <ind>**indicator**</ind> and <build>**build status**</build> files, thereby reducing the size of the repository 

<pre>
targets:

  <ind>1_data/out/compiled_data.rds.ind:</ind>
    command: gather_and_push_stream_data(
      ind_file = target_name,
      siteNumber = I('01118500'),
      parameterCd = I('00630'),
      startDate = I('1980-01-01'),
      endDate = I('2016-01-01'), 
      gd_config = <data>'lib/cfg/gd_config.yml'</data>)
      
  <data>1_data/out/compiled_data.rds:</data>
    command: gd_get(<ind>'1_data/out/compiled_data.rds.ind'</ind>, config_file = <data>'lib/cfg/gd_config.yml'</data>)

</pre>


### Pros and Cons 

####Advantages of a shared cache:

* Not every analyst needs to build every <target>**target**</target>, saving on total processing time.
* <target>**Targets**</target> that can only be built on specific operating systems (e.g., Mac) or in specific computing environments (e.g., a cluster) can still be accessible to all analysts for further analysis.
* Intermediate and final products can be immediately visible to anyone who has access to the shared cache, whether they are contributing to the analysis or simply inspecting/using the output.

####Disadvantages of a shared cache (as currently implemented):

* In a fast-paced collaborative development environment (e.g., a 'sprint'), it is challenging to maintain synchrony between the shared cache (the <data>**data**</data>) and the git repository (the metadata; <ind>**indicator**</ind> and <build>**build status**</build> files). Asynchrony is not a deal-breaker but does lead to more rebuilding than would be required for a slower-paced project. See *Common Pitfalls and Solutions* vignette. 
* Though we've done much to ensure this doesn't happen, it's conceivable that metadata will become corrupt relative to the data. Some monitoring and very occasional full rebuilding is recommended when practical.
* Old files no longer referenced by the code can accumulate on the shared cache unless manually deleted. Though these will not interfere with ongoing analysis, they can take up storage space unnecessarily.

##
